[package]
name = "slaq_macros"
description = "Proc macros for slaq"
version = "0.0.2"
edition = "2024"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
